accelerator: null
accumulate_grad_batches: 1
amp_backend: native
amp_level: O2
auto_lr_find: false
auto_scale_batch_size: false
auto_select_gpus: false
automatic_optimization: null
batch_size: 14
benchmark: false
chat: true
check_val_every_n_epoch: 1
checkpoint_callback: true
checkpoint_path: null
default_root_dir: logs
deterministic: false
distributed_backend: null
enable_pl_optimizer: null
fast_dev_run: false
flush_logs_every_n_steps: 100
gpus: 1
gradient_clip_val: 1.0
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
log_gpu_memory: null
logger: true
lr: 5.0e-05
max_epochs: 15
max_seq_len: 36
max_steps: null
min_epochs: null
min_steps: null
model_path: kobart_from_pretrained
move_metrics_to_cpu: false
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_processes: 1
num_sanity_val_steps: 2
num_workers: 5
overfit_batches: 0.0
plugins: null
precision: 32
prepare_data_per_node: true
process_position: 0
profiler: null
progress_bar_refresh_rate: null
reload_dataloaders_every_epoch: false
replace_sampler_ddp: true
resume_from_checkpoint: null
stochastic_weight_avg: false
subtask: NSMC
sync_batchnorm: false
terminate_on_nan: false
test_file: Chatbot_data/test.csv
tokenizer_path: emji_tokenizer
tpu_cores: !!python/name:pytorch_lightning.utilities.argparse._gpus_arg_default ''
track_grad_norm: -1
train_file: Chatbot_data/train.csv
truncated_bptt_steps: null
val_check_interval: 1.0
warmup_ratio: 0.1
weights_save_path: null
weights_summary: top
